version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:2.0.0
    restart: always
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - ENTRADA_NAMESERVERS=
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=graphite.example.com
            
      # The following options do NOT need to be changed
      - JAVA_OPTS=-Xmx4g -Xms4g
    volumes:
      # Map internal container path to a path on the host
      # format <host-path>:<container:path>
      # ENTRADA will write to /entrada/** in the container
      - /tmp/entrada/work:/entrada/data/work
      - /tmp/entrada/pcap:/entrada/data/input
      - /tmp/entrada/database:/entrada/data/output
      - /tmp/entrada/archive:/entrada/data/archive
      - /tmp/entrada/log:/entrada/data/log
    dns: 
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"
