version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:2.0.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=graphite.example.com
      - ENTRADA_ENGINE=hadoop
      - ENTRADA_NAMESERVERS=
      
      # PostgreSQL config options, make sure the the database is created before
      # starting the container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.example.com:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # Hadoop ( copy core-site.xml and hdfs-site.xml to the conf dir)
      - HDFS_NAMESERVICE_HOST=namenode.example.com
      - IMPALA_DAEMON_HOST=impala.example.com
      - ENTRADA_LOCATION_OUTPUT=hdfs://namenode.example.com:8020/user/entrada/database
      - HDFS_USERNAME=hdfs
      
      # If Kerberos is used provide credentials
      # AND place a keytab, krb5.conf and JAAS config files in the conf directory
      # make sure the keytab path in the JAAS config file uses internal container path: /entrada/conf
      - KERBEROS_REALM=MYREALM
      - KERBEROS_KEYTAB=/entrada/conf/keytab
      
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - JAVA_OPTS=-Xmx4g -Xms4g -Djava.security.krb5.conf=/entrada/conf/krb5.conf -Djava.security.auth.login.config=/entrada/conf/jaas.conf
    volumes:
      # Map internal container path to a path on the host
      # ENTRADA will write to /entrada/... in the container
      - /tmp/entrada/data/work:/entrada/data/work
      - /tmp/entrada/data/input:/entrada/data/input
      - /tmp/entrada/data/output:/entrada/data/output
      - /tmp/entrada/data/archive:/entrada/data/archive
      - /tmp/entrada/data/log:/entrada/data/log
      - /tmp/entrada/data/conf:/entrada/data/conf
    dns:
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"