version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:2.0.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=graphite.example.com
      - ENTRADA_ENGINE=hadoop
      - ENTRADA_NAMESERVERS=
      - ENTRADA_PCAP_ARCHIVE_MODE=archive
      - ENTRADA_ICMP_ENABLE=true
      - ENTRADA_INPUT_FILE_SKIPFIRST=false
      
      # PostgreSQL config options, make sure the the database is created before
      # starting the container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.example.com:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # Hadoop ( copy core-site.xml and hdfs-site.xml to the conf dir)
      - HDFS_NAMESERVICE_HOST=namenode.example.com
      - IMPALA_DAEMON_HOST=impalad.example.com
      - ENTRADA_LOCATION_OUTPUT=hdfs://namenode.example.com:8020/user/entrada/database
      - HDFS_USERNAME=hdfs
      
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - ENTRADA_LOCATION_WORK=/entrada/data/work
      - ENTRADA_LOCATION_INPUT=/entrada/data/input
      - ENTRADA_LOCATION_ARCHIVE=/entrada/data/archive
      - ENTRADA_LOCATION_LOG=/entrada/log
      - JAVA_OPTS=-Xmx4g -Xms4g
    volumes:
      # Map internal container path to a path on the host
      # ENTRADA will write to /entrada/... in the container
      - /tmp/entrada/data/work:/entrada/data/work
      - /tmp/entrada/data/pcap:/entrada/data/input
      - /tmp/entrada/data/database:/entrada/data/output
      - /tmp/entrada/data/archive:/entrada/data/archive
      - /tmp/entrada/data/log:/entrada/log
    dns:
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"