version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:2.0.0
    restart: always
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=graphite.example.com
      - ENTRADA_ENGINE=aws
      - ENTRADA_NAMESERVERS=
      
      # PostgreSQL config options, make sure the the database is created before 
      # starting the container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # AWS config options for S3 and Athena
      - AWS_ACCESS_KEY_ID=
	  - AWS_SECRET_KEY=
	  - AWS_BUCKET=entrada-data-myorg
      - ENTRADA_LOCATION_OUTPUT=s3://entrada-data-myorg/database/
      - ENTRADA_LOCATION_ARCHIVE=s3://entrada-data-myorg/archive/
       
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - JAVA_OPTS=-Xmx4g -Xms4g
    volumes:
      # Map internal container path to a path on the host
      # format <host-path>:<container:path>
      # ENTRADA will write to /entrada/... in the container
      # input, output and archive location can be on s3, then use s3 scheme s3://
      - /tmp/entrada/work:/entrada/data/work
      - /tmp/entrada/input:/entrada/data/input
      - /tmp/entrada/log:/entrada/data/log
    dns: 
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"
